spring:
  redis:
    password: ENC(kfdrfXyoFVGGC+8GWmANo0Mjo/aHhKfY)
    cluster:
      max-redirects: 8
      nodes: 172.21.34.129:6379,172.21.34.129:6380,172.21.34.166:6379,172.21.34.166:6380,172.21.34.212:6379,172.21.34.212:6380
    redisson:
      file: classpath:redisson-local.yaml
  datasource:
    url: jdbc:mysql:///SelfLearning?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ENC(TvvyfUP6Dm6oY1gdIWrfsw==)
    password: ENC(RADPWogpaBzKozEcf/33UU5WvKCnCLw6)
server:
  port: 11118
logging:
  config: classpath:logback-spring.xml
