server:
  port: 11118
spring:
  application:
    name: della
  redis:
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 60
    password: root
    host: 121.43.161.146

logging:
  config: classpath:logback-spring.xml
